def get_the_html(run_time, html_body_content):
    # We wrap everything in a main DIV with inline styles because Gmail
    # ignores <body> and <head> styles.

    html_output = f"""
    <!DOCTYPE html>
    <html lang="he" dir="rtl">
    <head>
        <meta charset="UTF-8">
        <title>News Summary</title>
    </head>
    <body style="margin: 0; padding: 0; background-color: #f4f4f4;">

        <div dir="rtl" style="
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            font-size: 18px;
            line-height: 1.6;
            color: #333333;
            max-width: 800px;
            margin: 20px auto;
            background-color: #ffffff;
            padding: 25px;
            border-radius: 10px;
            box-shadow: 0 4px 8px rgba(0,0,0,0.1);
        ">
            <h1 style="
                color: #0056b3;
                border-bottom: 2px solid #eeeeee;
                padding-bottom: 15px;
                margin-top: 0;
                font-size: 24px;
            ">
                סיכום חדשות - {run_time}
            </h1>

            <div style="margin-top: 20px;">
                {html_body_content}
            </div>

            <div style="
                margin-top: 40px;
                padding-top: 20px;
                border-top: 1px solid #eeeeee;
                font-size: 14px;
                color: #888888;
                text-align: center;
            ">
                Generated by AI News Bot
            </div>
        </div>
    </body>
    </html>
    """

    return html_output