import os
import re
import requests
import toml as tomlib


def get_telegram_secrets():
    # Try loading from secrets file first (Local dev)
    token = os.environ.get("TELEGRAM_BOT_TOKEN")
    chat_id = os.environ.get("TELEGRAM_CHAT_ID")

    # If not in env, try secrets.toml
    if not token or not chat_id:
        try:
            with open(".streamlit/secrets.toml", "r") as f:
                secrets = tomlib.load(f)
                token = secrets["secrets"].get("TELEGRAM_BOT_TOKEN")
                chat_id = secrets["secrets"].get("TELEGRAM_CHAT_ID")
        except Exception:
            pass

    if not token or not chat_id:
        print("[Telegram Error] Missing TELEGRAM_BOT_TOKEN or TELEGRAM_CHAT_ID.")
        return None, None

    return token, chat_id


def format_markdown_for_telegram(text: str) -> str:
    """
    Converts standard Markdown (generated by OpenAI) into Telegram-compatible HTML.
    Telegram HTML only supports <b>, <i>, <u>, <s>, <a>, <code>, <pre>.
    """
    # 0. Strip any stray markdown code fences the LLM might have injected
    cleaned = text.replace("```markdown", "").replace("```", "").strip()

    # 1. Convert ### Headers to HTML Bold
    cleaned = re.sub(r'^###\s+(.*)$', r'<b>\1</b>', cleaned, flags=re.MULTILINE)

    # 2. Convert ## Headers to HTML Bold
    cleaned = re.sub(r'^##\s+(.*)$', r'<b>\1</b>', cleaned, flags=re.MULTILINE)

    # 3. Standardize bullet points to a clean dot for Hebrew display
    cleaned = re.sub(r'^\*\s+', r'• ', cleaned, flags=re.MULTILINE)

    # 4. Standardize bold asterisks **text** to <b>text</b>
    cleaned = re.sub(r'\*\*(.*?)\*\*', r'<b>\1</b>', cleaned)

    # 5. Escape HTML characters (Telegram requires <, >, and & to be escaped)
    # But wait! We just added <b> tags, so let's temporarily replace them with placeholders
    cleaned = cleaned.replace('<b>', '[[B_START]]').replace('</b>', '[[B_END]]')
    
    cleaned = cleaned.replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;')
    
    # Put the <b> tags back
    cleaned = cleaned.replace('[[B_START]]', '<b>').replace('[[B_END]]', '</b>')

    return cleaned


def send_telegram_message(text: str, parse_mode: str = "HTML") -> bool:
    """
    Sends a message to the user via the Telegram Bot API.
    Splits the message if it exceeds Telegram's 4096 character limit.
    """
    token, chat_id = get_telegram_secrets()
    if not token or not chat_id:
        return False

    url = f"https://api.telegram.org/bot{token}/sendMessage"
    
    # Telegram max message length is 4096. We use 4000 to be safe with HTML tags.
    MAX_LENGTH = 4000
    
    # Split text into chunks, trying to break at newlines to keep HTML tags intact
    chunks = []
    current_chunk = ""
    
    for line in text.split('\n'):
        if len(current_chunk) + len(line) + 1 > MAX_LENGTH:
            if current_chunk:
                chunks.append(current_chunk)
                current_chunk = line + "\n"
            else:
                # If a single line is longer than MAX_LENGTH, hard split it
                chunks.append(line[:MAX_LENGTH])
                current_chunk = line[MAX_LENGTH:] + "\n"
        else:
            current_chunk += line + "\n"
            
    if current_chunk.strip():
        chunks.append(current_chunk.strip())

    success_all = True
    for idx, chunk in enumerate(chunks):
        payload = {
            "chat_id": chat_id,
            "text": chunk,
            "parse_mode": parse_mode
        }
        
        try:
            response = requests.post(url, json=payload)
            response.raise_for_status()
            print(f"[Telegram Success] Message chunk {idx+1}/{len(chunks)} sent successfully.")
        except requests.exceptions.HTTPError as e:
            print(f"[Telegram Error] HTTP Error on chunk {idx+1}: {e.response.text}")
            success_all = False
        except Exception as e:
            print(f"[Telegram Error] Failed to send msg chunk {idx+1}: {e}")
            success_all = False
            
    return success_all


if __name__ == "__main__":
    # Test block
    test_msg = """
## 📱 מבזקי חדשות טלגרם

### ביטחון וצבא
* מבזק עובדתי ומפורט: יירוט מוצלח בשמי הצפון.
* **עדכון:** הכל תקין. <bold>test</bold> & other symbols.
    """
    formatted = format_markdown_for_telegram(test_msg)
    print("Formatted Text:")
    print(formatted)
    # send_telegram_message(formatted) # Uncomment to test sending
